[Distribution]
Distribution=debian
Release=bookworm

[Output]
Format=disk
ImageId=debian12

[Build]
ToolsTree=yes
ToolsTreePackages=systemd-boot-unsigned

[Content]
Packages=
    systemd
    systemd-boot
    systemd-sysv
    udev
    linux-image-amd64
    dracut
    e2fsprogs
    dosfstools
    iproute2
    iputils-ping
    openssh-server
    passwd
    sudo
    vim-tiny
    qemu-guest-agent
Bootable=yes
