[Distribution]
Distribution=ubuntu
Release=noble

[Output]
Format=disk
ImageId=ubuntu2404

[Build]
ToolsTree=yes
ToolsTreePackages=systemd-boot-unsigned

[Content]
Packages=
    systemd
    systemd-boot
    systemd-sysv
    udev
    linux-image-generic
    dracut
    e2fsprogs
    dosfstools
    iproute2
    iputils-ping
    openssh-server
    passwd
    sudo
    vim-tiny
    qemu-guest-agent
Bootable=yes
