[Distribution]
Distribution=fedora
Release=41

[Output]
Format=disk
ImageId=fedora41-minimal

[Build]
ToolsTree=yes
ToolsTreePackages=systemd-boot-unsigned

[Content]
Packages=
    systemd
    systemd-udev
    kernel
    dracut
    e2fsprogs
    dosfstools
    util-linux
    iproute
    openssh-server
    passwd
    shadow-utils
    qemu-guest-agent
Bootable=yes
